apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-app
  labels: 
    app: fe-app
  namespace: fe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fe-app
  template:
    metadata:
        labels:
          app: fe-app
    spec:
      containers:
        - name: fe-app-container
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: fe-app-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: fe-app-volume
          emptyDir:
            sizeLimit: 500Mi

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort 
  selector:
    app: fe-app
  ports:
    - protocol: TCP
      targetPort: 80
      port: 80
      name: http
